version: '3'

services:
  eventpublisherapp:
    image: eventpublisherapp
    ports:
      - "32822:32822"
    build:
      context: .
      dockerfile: Sample/EventPublisherApp/Dockerfile
    depends_on:
      - rabbitmq

  eventconsumerapp:
    image: eventconsumerapp
    ports:
      - "32821:32821"
    build:
      context: .
      dockerfile: Sample/EventConsumerApp/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
